### ISSUE TITLE
Name light_level_sensor:sensor does not follow naming conventions: "lls:" or ":" prefix required

### ISSUE THREAD

**Issue by rusty-snake** [Nifty-Neutron/Minetest-Light-Level-Sensor#1]
**Describe the bug**
Mod could not be loaded: `Name light_level_sensor:sensor does not follow naming conventions: "lls:" or ":" prefix required`

**To Reproduce**
- Install this mod from contentdb
- Create a new world
- Enable this mod
- Start world

**Expected behavior**
Mod allows server to start.

**MineTest version**
MineTest 5.2.0 (fedora package)

**debug.txt content**
```
ERROR[Main]: ModError: Failed to load and run script from /home/user/.minetest/mods/lls/init.lua:
ERROR[Main]: /usr/share/minetest/builtin/game/register.lua:65: Name light_level_sensor:sensor does not follow naming conventions: "lls:" or ":" prefix required
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'error'
ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:65: in function 'check_modname_prefix'
ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:115: in function 'register_item'
ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:220: in function 'register_craftitem'
ERROR[Main]: 	/home/orion/.minetest/mods/lls/init.lua:2: in main chunk
ERROR[Main]: Siehe debug.txt für Details.
```

**Additional context**

**Comment by Nifty-Neutron** [comment]
Fixed in https://github.com/Nifty-Neutron/Minetest-Light-Level-Sensor/commit/cd8720963d2ad6922a38b729bf5891a34bb7698f
please update to the latest version.
and thanks for using the mod
and helping the development!
